/* ============================================================
   DATA
   ============================================================ */

const trip = [
  // DAY 1
  { day: 1, name: "Shibuya Crossing", coords: [35.6595, 139.7005], category: "viewpoint",
    tagline: "World's busiest pedestrian scramble",
    desc: "Walk it once at street level, then watch from above. Iconic from every Tokyo movie.",
    hours: "24/7", cost: "Free",
    tip: "Most chaotic Fri/Sat nights 9–11pm. Best aerial view: MAG's Park rooftop or Starbucks Tsutaya 2F." },
  { day: 1, name: "MAG's Park (Magnet by Shibuya109)", coords: [35.6597, 139.6995], category: "viewpoint",
    tagline: "Rooftop overlooking the Crossing",
    desc: "Rooftop deck above Shibuya109 with the best free-ish view directly down onto the Crossing.",
    hours: "10:00 AM – 9:00 PM", cost: "¥600",
    tip: "Cheaper and less crowded than Shibuya Sky for the Crossing-specific view." },
  { day: 1, name: "Miyashita Park", coords: [35.6606, 139.7028], category: "shopping",
    tagline: "Linear rooftop park + boutique mall",
    desc: "Three-block-long elevated park over a stylish mall. Skate ramp, climbing wall, rooftop bars.",
    hours: "Park 24/7; shops 11 AM – 9 PM", cost: "Free",
    tip: "The rooftop bar strip is fun for a casual first-night drink." },
  { day: 1, name: "Gyukatsu Motomura Shibuya", coords: [35.6580, 139.7008], category: "food",
    tagline: "Crispy panko-fried wagyu",
    desc: "Tonkatsu but with rare beef — you cook each slice on a small charcoal stone at your table.",
    hours: "11 AM – 10 PM", cost: "¥1,800–2,500",
    tip: "Lines move fast. Order the 130g set; the 200g is more meat than enjoyment." },
  { day: 1, name: "Kaiten Sushi Ginza Onodera", coords: [35.6588, 139.7016], category: "food",
    tagline: "High-end conveyor sushi",
    desc: "Premium kaiten sushi from a Michelin-affiliated group. Sit at the counter and watch.",
    hours: "11 AM – 10 PM", cost: "¥3,000–6,000",
    tip: "Reserve via website if you can; walk-ins wait 30–60 min at peak." },

  // DAY 2
  { day: 2, name: "Meiji Shrine", coords: [35.6764, 139.6993], category: "shrine",
    tagline: "Tokyo's grandest forest shrine",
    desc: "Shinto shrine dedicated to Emperor Meiji, set inside a 170-acre forest in the middle of Tokyo.",
    hours: "Sunrise – sunset (~6 AM – 5:30 PM)", cost: "Free",
    tip: "Go early for empty paths. Sake barrel wall is the photo spot." },
  { day: 2, name: "Takeshita Street", coords: [35.6710, 139.7036], category: "shopping",
    tagline: "Harajuku's neon teen street",
    desc: "400m pedestrian alley of crepe stands, kawaii fashion, and chaos. Peak Harajuku.",
    hours: "Most shops 10 AM – 8 PM", cost: "Free to walk",
    tip: "Skip on weekends if crowds drain you. Marion Crêpes is the original." },
  { day: 2, name: "Omotesando", coords: [35.6657, 139.7124], category: "shopping",
    tagline: "Tokyo's Champs-Élysées",
    desc: "Tree-lined boulevard of architect-designed flagship stores (Prada, Tod's, Dior).",
    hours: "Shops 11 AM – 8 PM", cost: "Free",
    tip: "Look up — the buildings are the attraction. Omotesando Hills mall is worth a wander." },
  { day: 2, name: "Shibuya PARCO", coords: [35.6620, 139.6985], category: "shopping",
    tagline: "Nintendo / Pokémon / Jump Shop tower",
    desc: "Mall containing the official Nintendo Tokyo store, Pokémon Center, and Jump Shop (manga merch).",
    hours: "11 AM – 9 PM", cost: "Free entry",
    tip: "Nintendo store has Tokyo-exclusive merch. Lines on weekends." },
  { day: 2, name: "Shibuya Sky", coords: [35.6586, 139.7019], category: "viewpoint",
    tagline: "Open-air rooftop observation deck",
    desc: "230m open-air rooftop atop Shibuya Scramble Square. The view straight down at the Crossing is unreal.",
    hours: "10 AM – 10:30 PM (last entry 9:20)", cost: "¥2,500",
    tip: "Book the sunset slot online in advance — it sells out weeks ahead. Bring a jacket; it's windy." },

  // DAY 3
  { day: 3, name: "Tsukiji Outer Market", coords: [35.6655, 139.7707], category: "food",
    tagline: "Street food market, ex-fish-market grounds",
    desc: "Maze of stalls: tamagoyaki on a stick, fresh oysters, tuna skewers, sea urchin bowls.",
    hours: "5 AM – 2 PM (best 7–10 AM)", cost: "¥200–2,000 per item",
    tip: "Most stalls cash only. Try Sushidai or Daiwa for sit-down sushi if lines aren't insane." },
  { day: 3, name: "Ginza", coords: [35.6717, 139.7649], category: "shopping",
    tagline: "Tokyo's upscale shopping district",
    desc: "Department stores, flagship boutiques, art galleries, and traditional stationery shops.",
    hours: "Most shops 10 AM – 8 PM", cost: "Free to walk",
    tip: "Itoya stationery (G.Itoya) is the cathedral of Japanese paper goods — 12 floors." },
  { day: 3, name: "Uniqlo Ginza Flagship", coords: [35.6707, 139.7649], category: "shopping",
    tagline: "12-floor Uniqlo flagship",
    desc: "The largest Uniqlo on the planet. Tokyo-only collabs, custom embroidery, tax-free counter.",
    hours: "11 AM – 9 PM", cost: "Free entry",
    tip: "Get the tax-free discount with your passport at checkout." },
  { day: 3, name: "Art Aquarium Museum", coords: [35.6735, 139.7700], category: "cultural",
    tagline: "Goldfish + light installation",
    desc: "Surreal indoor exhibit of thousands of goldfish in illuminated tanks designed by artists.",
    hours: "10 AM – 7 PM", cost: "¥2,500",
    tip: "Photogenic but small — allow 60–90 min. Book online to skip ticket line." },
  { day: 3, name: "Tokyo Tower", coords: [35.6586, 139.7454], category: "viewpoint",
    tagline: "Tokyo's red Eiffel-style tower",
    desc: "333m steel tower from 1958. Less hyped than Skytree, but better photogenic-from-below shots.",
    hours: "9 AM – 10:30 PM", cost: "¥1,200 main / ¥3,000 top",
    tip: "Photograph from Roppongi Hills or from Zojoji Temple grounds at the base." },

  // DAY 4
  { day: 4, name: "Tokyo Metropolitan Government Building", coords: [35.6896, 139.6918], category: "viewpoint",
    tagline: "Free observation deck, 202m",
    desc: "Two free observation decks on the 45th floor. On clear days you can see Mt. Fuji.",
    hours: "9:30 AM – 10 PM", cost: "Free",
    tip: "Best free Tokyo view. Mt. Fuji visible mostly Dec–Feb mornings." },
  { day: 4, name: "Omoide Yokocho", coords: [35.6921, 139.6990], category: "food",
    tagline: "'Memory Lane' yakitori alley",
    desc: "Narrow alley of tiny smoky yakitori counters under the Shinjuku tracks since the postwar years.",
    hours: "5 PM – midnight", cost: "¥2,000–4,000",
    tip: "Most stalls seat 6–10 people. No reservations. Cash. Smoke-saturated clothes after." },
  { day: 4, name: "Akihabara", coords: [35.6987, 139.7731], category: "entertainment",
    tagline: "Electric Town / anime / gaming",
    desc: "Multi-floor anime stores, retro arcades (Super Potato, Taito), figure shops, maid cafés.",
    hours: "Most stores 10 AM – 10 PM", cost: "Free to wander",
    tip: "Super Potato (3 floors of retro games), Mandarake Complex (8 floors), Yodobashi-Akiba." },
  { day: 4, name: "JDM Rental — Omoshi Rent-A-Car", coords: [35.6263, 139.6764], category: "entertainment",
    tagline: "Late-night JDM sports car rental",
    desc: "Pick up a Supra / GT-R / RX-7 / Civic Type R and drive the Shuto Expressway loop.",
    hours: "Late evening pickups, returns by 2–3 AM", cost: "¥20,000–60,000 / 3 hrs",
    tip: "Requires International Driving Permit (get from CAA in Canada before leaving). Book weeks ahead." },
  { day: 4, name: "Daikoku Parking Area", coords: [35.4509, 139.6856], category: "entertainment",
    tagline: "Legendary Yokohama car meet spot",
    desc: "Loop-shaped PA on the Wangan/Bayshore expressway. Spontaneous JDM/tuner meets Fri & Sat nights.",
    hours: "24/7 (best 10 PM – 2 AM Fri/Sat)", cost: "Free with car",
    tip: "Only accessible from the expressway — can't be reached by normal car/taxi. Aim for the loop on a JDM rental night." },

  // DAY 5
  { day: 5, name: "Lake Kawaguchi", coords: [35.5104, 138.7522], category: "natural",
    tagline: "Fuji's iconic reflection lake",
    desc: "Largest of the Fuji Five Lakes. Pristine reflections of Fuji on still mornings.",
    hours: "24/7", cost: "Free",
    tip: "Walk or bike the north shore for best Fuji views. Oishi Park is a top photo spot." },
  { day: 5, name: "Lawson Fujikawaguchiko (the viral one)", coords: [35.4994, 138.7682], category: "viewpoint",
    tagline: "The Lawson convenience store + Fuji photo",
    desc: "The Lawson with the perfect Mt. Fuji backdrop. Famously over-touristed (they put up a barrier in 2024).",
    hours: "24/7", cost: "Free",
    tip: "Crowded mid-morning. Try early dawn for a clear shot." },
  { day: 5, name: "Chureito Pagoda", coords: [35.5114, 138.7965], category: "viewpoint",
    tagline: "Pagoda + Fuji + cherry blossoms cliché shot",
    desc: "Five-storied pagoda on a hillside with Fuji behind. The most photographed angle in Japan.",
    hours: "24/7", cost: "Free (398 steps up)",
    tip: "Sunrise is unreal. Crowds peak around 9–11 AM." },

  // DAY 6
  { day: 6, name: "Dotonbori", coords: [34.6687, 135.5011], category: "entertainment",
    tagline: "Osaka's neon canal nightlife strip",
    desc: "Glico Running Man sign, giant crab signs, takoyaki, okonomiyaki, and a million tourists.",
    hours: "24/7 (best 6 PM – midnight)", cost: "Free to walk",
    tip: "Eat your way down the strip. Avoid the obvious tourist traps; pick stalls with locals queueing." },
  { day: 6, name: "Shinsaibashi", coords: [34.6747, 135.5008], category: "shopping",
    tagline: "600m covered shopping arcade",
    desc: "Connects to Dotonbori. Department stores, fashion, drugstores (huge for Japanese skincare hauls).",
    hours: "Most shops 11 AM – 9 PM", cost: "Free",
    tip: "Don Quijote in Dotonbori is the chaotic souvenir mecca." },

  // DAY 7
  { day: 7, name: "Kuromon Ichiba Market", coords: [34.6657, 135.5061], category: "food",
    tagline: "Osaka's kitchen — 600m food market",
    desc: "Fresh seafood, wagyu skewers, fruit stalls, takoyaki. Most stalls grill on the spot.",
    hours: "9 AM – 6 PM", cost: "¥300–2,000 per item",
    tip: "Best 10 AM – 1 PM. Try the grilled scallops and uni shooters." },
  { day: 7, name: "Den Den Town", coords: [34.6603, 135.5046], category: "entertainment",
    tagline: "Osaka's Akihabara (anime/electronics)",
    desc: "Quieter and more local than Akihabara — better for genuine collectors, less performative.",
    hours: "Most stores 11 AM – 8 PM", cost: "Free to wander",
    tip: "Super Kids Land (Joshin), Mandarake, Animate Osaka." },
  { day: 7, name: "Studio Ghibli Donguri Republic", coords: [34.6604, 135.5048], category: "shopping",
    tagline: "Official Ghibli merch store",
    desc: "Totoro, No-Face, Kiki — all the merch. There are multiple locations; Den Den is one.",
    hours: "11 AM – 8 PM", cost: "Free entry",
    tip: "Larger Donguri at Osaka Station's Tenpos Sky if this one's mobbed." },
  { day: 7, name: "Yakiniku M Namba", coords: [34.6664, 135.5009], category: "food",
    tagline: "Premium A5 wagyu yakiniku",
    desc: "Highly-rated Osaka yakiniku — grill your own A5 wagyu cuts at the table.",
    hours: "5 PM – 11 PM", cost: "¥6,000–12,000 / person",
    tip: "Reserve. Order the omakase course to taste range without decision fatigue." },

  // DAY 8
  { day: 8, name: "Osaka Castle", coords: [34.6873, 135.5262], category: "cultural",
    tagline: "16th-century reconstructed castle",
    desc: "Hideyoshi's castle, rebuilt in concrete in 1931. Museum inside, panoramic view from the top.",
    hours: "9 AM – 5 PM", cost: "¥600 (grounds free)",
    tip: "The exterior is the photo. Interior is a fine museum but skippable if short on time." },
  { day: 8, name: "Umeda Sky Building", coords: [34.7053, 135.4900], category: "viewpoint",
    tagline: "Twin towers w/ open-air ring deck",
    desc: "173m bridge between two towers with an open-air rooftop. Best sunset spot in Osaka.",
    hours: "9:30 AM – 10:30 PM", cost: "¥2,000",
    tip: "Go up 60 min before sunset. The escalator-in-the-sky is half the experience." },

  // DAY 9
  { day: 9, name: "Kiyomizu-dera", coords: [34.9949, 135.7850], category: "shrine",
    tagline: "Wooden temple on a cliff",
    desc: "Famous wooden stage jutting out over the hillside with panoramic views over Kyoto.",
    hours: "6 AM – 6 PM", cost: "¥400",
    tip: "Go at opening or after 4 PM. By 9 AM it's packed shoulder-to-shoulder." },
  { day: 9, name: "Sannenzaka & Ninenzaka", coords: [34.9966, 135.7800], category: "cultural",
    tagline: "Preserved stone-paved old streets",
    desc: "Two atmospheric sloped lanes lined with wooden machiya houses and traditional shops.",
    hours: "Walkable 24/7; shops ~10 AM – 6 PM", cost: "Free",
    tip: "Wear shoes you can take off — many shops require it. Crowded midday." },
  { day: 9, name: "Hōkan-ji (Yasaka Pagoda)", coords: [34.9985, 135.7798], category: "shrine",
    tagline: "Five-storied pagoda in old Kyoto",
    desc: "Iconic 46m pagoda framed at the end of Yasaka Street. The Kyoto-postcard photo.",
    hours: "Exterior 24/7", cost: "Free to view",
    tip: "Best shot looking down Yasaka Street toward it. Early morning, no people." },
  { day: 9, name: "Gion", coords: [35.0036, 135.7747], category: "cultural",
    tagline: "Kyoto's geisha district",
    desc: "Wooden teahouses, lantern-lit lanes. Walk Hanamikoji Street at dusk for the classic atmosphere.",
    hours: "Always; magical 5–8 PM", cost: "Free",
    tip: "Don't chase geiko/maiko for photos — there's an actual ¥10,000 fine now. Just observe." },
  { day: 9, name: "Yasaka Shrine", coords: [35.0036, 135.7785], category: "shrine",
    tagline: "Lantern-lit shrine at edge of Gion",
    desc: "Main shrine of the Gion district, beautifully lit at night with hundreds of lanterns.",
    hours: "24/7", cost: "Free",
    tip: "Adjacent Maruyama Park is famous for cherry blossoms in spring." },
  { day: 9, name: "Pontocho Alley", coords: [35.0086, 135.7714], category: "food",
    tagline: "Narrow lantern-lit dining alley",
    desc: "One block wide, three blocks long — high-end kaiseki, casual yakitori, riverside terraces.",
    hours: "Mostly 5 PM – midnight", cost: "¥3,000–15,000",
    tip: "Summer (May–Sep) terraces over the Kamogawa River are unbeatable." },

  // DAY 10
  { day: 10, name: "Fushimi Inari Taisha", coords: [34.9671, 135.7727], category: "shrine",
    tagline: "10,000 vermillion torii gates",
    desc: "Endless tunnels of torii gates climbing Mt. Inari. The whole loop takes 2–3 hours.",
    hours: "24/7", cost: "Free",
    tip: "GO BEFORE 7 AM. The empty-trails photos you've seen on Instagram require dawn arrival." },
  { day: 10, name: "Arashiyama Bamboo Grove", coords: [35.0170, 135.6716], category: "natural",
    tagline: "Towering bamboo forest path",
    desc: "Atmospheric 500m walking path through giant bamboo. Famous for the light filtering through.",
    hours: "24/7", cost: "Free",
    tip: "Same rule as Fushimi — arrive by 7:30 AM or you'll be in a tour-group conga line." },
  { day: 10, name: "Tenryū-ji", coords: [35.0157, 135.6738], category: "shrine",
    tagline: "Zen temple with iconic garden",
    desc: "UNESCO Zen temple. The Sōgenchi Garden is one of Japan's oldest, designed in 1339.",
    hours: "8:30 AM – 5 PM", cost: "¥500 garden / ¥800 +buildings",
    tip: "Walk through the garden, exit the back gate — drops you straight into the bamboo grove." },
  { day: 10, name: "Togetsukyo Bridge", coords: [35.0131, 135.6779], category: "viewpoint",
    tagline: "'Moon Crossing Bridge'",
    desc: "155m bridge over the Hozu River, with forested mountains behind. The Arashiyama postcard shot.",
    hours: "24/7", cost: "Free",
    tip: "Best from the north bank looking south. Riverside cafés on the south side." },

  // DAY 11
  { day: 11, name: "Nanzen-ji", coords: [35.0114, 135.7937], category: "shrine",
    tagline: "Zen temple complex with aqueduct",
    desc: "Sprawling temple grounds with a Meiji-era brick aqueduct cutting through — surreal combo.",
    hours: "8:40 AM – 5 PM", cost: "Grounds free; sub-temples ¥600 each",
    tip: "The aqueduct + autumn leaves combo (mid-Nov) is one of Kyoto's best photo ops." },
  { day: 11, name: "Eikan-dō (Zenrin-ji)", coords: [35.0151, 135.7948], category: "shrine",
    tagline: "Maple temple par excellence",
    desc: "Famous for fall foliage — over 3,000 maple trees turn red in November.",
    hours: "9 AM – 5 PM", cost: "¥600 (¥1,000 in autumn season)",
    tip: "Worth visiting even out of season — the gardens and pagoda viewpoint are beautiful year-round." },
  { day: 11, name: "Philosopher's Path", coords: [35.0231, 135.7948], category: "natural",
    tagline: "Canal-side walking path",
    desc: "2km stone path along a cherry-tree-lined canal between Nanzen-ji and Ginkaku-ji.",
    hours: "24/7", cost: "Free",
    tip: "Cafés and craft shops dotted along the way. Best in cherry blossom (early Apr) or autumn." },
  { day: 11, name: "Kifune Shrine", coords: [35.1217, 135.7625], category: "shrine",
    tagline: "Mountain shrine, red-lantern staircase",
    desc: "Mystical shrine in the cedar-forested mountains north of Kyoto. The lantern-lit stone steps are iconic.",
    hours: "6 AM – 8 PM (lanterns lit at dusk)", cost: "Free",
    tip: "Rainy/misty days are atmospheric, not a problem. Combine with Kurama Temple via the mountain trail." },
  { day: 11, name: "Toei Kyoto Studio Park (Eigamura)", coords: [35.0162, 135.7050], category: "entertainment",
    tagline: "Edo-era film set + samurai sword lessons",
    desc: "Working samurai-film studio open to the public. Offers actual sword-fighting lessons with film props.",
    hours: "9 AM – 5 PM", cost: "¥2,400 admission; sword lesson ~¥3,000 extra",
    tip: "Book the sword lesson in advance via the website. Good rainy-day backup activity." },

  // DAY 12
  { day: 12, name: "Shin-Kobe Ropeway", coords: [34.7079, 135.1953], category: "viewpoint",
    tagline: "Ropeway to Nunobiki Herb Garden",
    desc: "Cable car up the mountain behind Shin-Kobe Station. Sweeping views of Kobe and Osaka Bay.",
    hours: "9:30 AM – 5 PM (later in summer)", cost: "¥1,800 round-trip",
    tip: "Take the ropeway up, walk down through the herb garden, exit via Nunobiki Falls." },
  { day: 12, name: "Nunobiki Falls", coords: [34.7110, 135.1959], category: "natural",
    tagline: "43m waterfall, 10-min from Shin-Kobe",
    desc: "Four-tiered waterfall in a forested ravine, surprisingly close to the city. Walking path from the ropeway.",
    hours: "24/7", cost: "Free",
    tip: "Wear shoes with grip — paths can be wet. Easy 15-min descent from the herb garden." },
  { day: 12, name: "Kobe Beef Lunch (Wakkoqu / Steakland)", coords: [34.6951, 135.1955], category: "food",
    tagline: "A5 Kobe beef teppanyaki",
    desc: "The reason you're in Kobe. Multiple legendary spots — Wakkoqu Shin-Kobe is most accessible.",
    hours: "11 AM – 10 PM", cost: "¥6,000–20,000 lunch course",
    tip: "Lunch sets are dramatically cheaper than dinner for the same beef. Reserve." },
  { day: 12, name: "Arima Onsen", coords: [34.7989, 135.2467], category: "onsen",
    tagline: "Japan's oldest hot spring town",
    desc: "1,300-year-old onsen village. Two waters: 'kinsen' (gold, iron-rich) and 'ginsen' (silver, clear).",
    hours: "Public baths typically 9 AM – 9 PM", cost: "¥800–1,500 day use",
    tip: "Kin-no-Yu (gold) and Gin-no-Yu (silver) are the two municipal baths — try both. Bring small towel." },

  // DAY 13
  { day: 13, name: "Daimon-zaka", coords: [33.6650, 135.8918], category: "cultural",
    tagline: "Cedar-lined stone pilgrim path",
    desc: "Ancient stone-paved pilgrimage path leading up to Kumano Nachi Taisha. 600m climb.",
    hours: "24/7", cost: "Free",
    tip: "You can rent traditional Heian pilgrim costumes nearby for the climb (touristy but fun)." },
  { day: 13, name: "Kumano Nachi Taisha", coords: [33.6700, 135.8908], category: "shrine",
    tagline: "Top shrine of the Kumano Kodo",
    desc: "One of three grand Kumano shrines. UNESCO listed as part of the Kii pilgrimage routes.",
    hours: "5 AM – 4:30 PM", cost: "Free (¥300 treasure hall)",
    tip: "From the shrine plaza you get THE shot: pagoda framed against the waterfall." },
  { day: 13, name: "Seiganto-ji Pagoda + Nachi Falls view", coords: [33.6701, 135.8910], category: "viewpoint",
    tagline: "Three-story pagoda with waterfall behind",
    desc: "Iconic three-tiered red pagoda with 133m Nachi Falls plummeting directly behind it.",
    hours: "8 AM – 4 PM", cost: "¥300 pagoda climb",
    tip: "This is THE photo from Wakayama. Aim for mid-morning when the light is on the pagoda face." },
  { day: 13, name: "Nachi Falls (base)", coords: [33.6716, 135.8919], category: "natural",
    tagline: "133m — Japan's tallest single-drop waterfall",
    desc: "Sacred waterfall, object of Shinto worship. You can pay ¥300 to access a closer viewing platform.",
    hours: "8:30 AM – 4 PM", cost: "Free / ¥300 closer view",
    tip: "Allow 30–45 min after the shrine + pagoda. Bus connects Kii-Katsuura station to the area." },

  // DAY 14
  { day: 14, name: "Sakino-yu Onsen", coords: [33.6772, 135.3457], category: "onsen",
    tagline: "Ocean-front rotenburo, ¥500",
    desc: "Outdoor onsen on a rocky outcropping over the Pacific. Listed as one of Japan's oldest baths.",
    hours: "7 AM – 5 PM (Apr–Sep until 6); closed Wed", cost: "¥500",
    tip: "Bring your own towel and small change. Don't bring valuables — open lockers only." },
  { day: 14, name: "Sandanbeki Cliffs", coords: [33.6794, 135.3447], category: "natural",
    tagline: "50m sea cliffs + hidden cave",
    desc: "Dramatic cliffs with a cave 36m below — accessible via elevator, used by samurai-era pirates.",
    hours: "8 AM – 5 PM", cost: "¥1,500 cave / cliffs free",
    tip: "Cliffs are spectacular for free. The cave elevator is overpriced for what it is." },
  { day: 14, name: "Engetsu Island", coords: [33.6890, 135.3408], category: "natural",
    tagline: "Sea-arch island, sunset spot",
    desc: "Tiny island with a natural arch eroded through the middle. Sunset alignment in summer = unreal.",
    hours: "24/7 (view from shore)", cost: "Free",
    tip: "Time your visit for sunset if you can. Otherwise, daytime is still very photogenic." },

  // DAY 15
  { day: 15, name: "Nakanoshima (slow Osaka morning)", coords: [34.6925, 135.4965], category: "cultural",
    tagline: "Island park between two rivers",
    desc: "Quieter side of Osaka — museums, cafés, gardens. Good for a slow recovery day.",
    hours: "24/7", cost: "Free",
    tip: "Museum of Oriental Ceramics is small but excellent. Rose garden is free." },
  { day: 15, name: "Shinsekai / Tsutenkaku Tower", coords: [34.6526, 135.5063], category: "cultural",
    tagline: "Retro 1950s Osaka neighborhood",
    desc: "Showa-era atmosphere — kushikatsu joints, retro signage, the 'New World' tower.",
    hours: "Most shops 11 AM – 10 PM", cost: "Free (tower ¥900)",
    tip: "Kushikatsu Daruma is the original deep-fried-skewers chain — eat there." },

  // DAY 16
  { day: 16, name: "Kansai International Airport (KIX)", coords: [34.4347, 135.2329], category: "transit",
    tagline: "Departure airport",
    desc: "Kansai's main international airport, built on an artificial island.",
    hours: "24/7", cost: "—",
    tip: "Nankai Rapi:t from Namba: 40 min, ¥1,490, reservable. Be there 3 hrs before international flight." }
];

/* ============================================================
   CONFIG
   ============================================================ */

const CATEGORIES = {
  shrine:        { color: "#dc2626", symbol: "⛩",  label: "Shrine / Temple" },
  food:          { color: "#ea580c", symbol: "🍜", label: "Food / Restaurant" },
  viewpoint:     { color: "#0284c7", symbol: "🌆", label: "Viewpoint" },
  shopping:      { color: "#9333ea", symbol: "🛍", label: "Shopping" },
  onsen:         { color: "#db2777", symbol: "♨",  label: "Onsen" },
  entertainment: { color: "#ca8a04", symbol: "🎮", label: "Entertainment" },
  cultural:      { color: "#92400e", symbol: "🏛", label: "Cultural / Museum" },
  natural:       { color: "#16a34a", symbol: "🗻", label: "Natural Landmark" },
  transit:       { color: "#525252", symbol: "✈",  label: "Transit / Airport" },
  lodging:       { color: "#0d9488", symbol: "🛏", label: "Lodging" },
};

// Day colors: blue (1) → red (16)
function dayColor(day) {
  const t = (day - 1) / 15; // 0..1
  // interpolate hue from blue (220) to red (0) via 180 (cyan) → 60 (yellow) → 0 (red)
  // simpler: HSL hue 215 -> 0
  const hue = 215 - (215 * t);
  return `hsl(${hue}, 72%, 50%)`;
}
